#!/usr/bin/env python3
"""Render the extracted brick/workflow dependency model as Mermaid."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from tools.model_repository import RepositoryModel, build_model
except ModuleNotFoundError:  # Direct execution adds tools/, not the repo root.
    from model_repository import RepositoryModel, build_model  # type: ignore[no-redef]


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', "&quot;")


def render(model: RepositoryModel) -> str:
    bricks = [item for item in model.packages if item.kind == "brick"]
    workflows = [item for item in model.packages if item.kind == "workflow"]
    by_name = {item.name: item for item in model.packages}
    lines = [
        "%% Generated by tools/graph_bricks.py from host-language contracts.",
        "flowchart TD",
        "    subgraph workflow_layer[Workflows]",
    ]
    for item in workflows:
        lines.append(f'        workflow_{item.name}["{escape(item.name)}"]')
    lines.extend(["    end", "", "    subgraph brick_layer[Bricks]"])
    for item in bricks:
        label = "<br/>".join([escape(item.name), *(escape(value) for value in item.owned_state)])
        lines.append(f'        brick_{item.name}["{label}"]')
    lines.append("    end")
    edges: list[str] = []
    for item in model.packages:
        source = f"brick_{item.name}" if item.kind == "brick" else f"workflow_{item.name}"
        for dependency in item.dependencies:
            target = by_name.get(dependency)
            if target is not None:
                edges.append(f"    {source} --> brick_{target.name}")
    if edges:
        lines.extend(["", *edges])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    print(render(build_model(parser.parse_args().root.resolve())), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
