#!/usr/bin/env python3
"""Render brick and workflow dependencies as Mermaid using the contract parser."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

try:
    from tools import lint_bricks
except ModuleNotFoundError:  # Direct execution adds tools/, not the repo root.
    import lint_bricks  # type: ignore[no-redef]


def read_contract(brick: Path) -> tuple[dict[str, str], tuple[str, ...]]:
    """Read dependency and ownership literals from one contract.bend."""
    root = brick.parents[1]
    lint = lint_bricks.Lint(root)
    contract = lint_bricks.lint_contract(brick, lint)
    if lint.errors:
        return {}, ()
    return contract.dependencies, contract.owned_state


def read_workflow_contract(workflow: Path) -> tuple[str, ...]:
    """Read the literal brick dependency list from one workflow contract."""
    root = workflow.parents[1]
    lint = lint_bricks.Lint(root)
    contract = lint_bricks.lint_workflow_contract(workflow, lint)
    return () if lint.errors else contract.dependencies


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', "&quot;")


def node_label(name: str, owned_state: tuple[str, ...]) -> str:
    return "<br/>".join([escape(name), *(escape(item) for item in owned_state)])


def render(
    contracts: dict[str, tuple[dict[str, str], tuple[str, ...]]],
    workflows: dict[str, tuple[str, ...]] | None = None,
) -> str:
    workflows = workflows or {}
    names = sorted(contracts)
    depended_on = {
        dependency
        for dependencies, _ in contracts.values()
        for dependency in dependencies
        if dependency in contracts
    }
    lines = [
        "%% Generated by tools/graph_bricks.py. Workflows compose bricks; solid: orchestrated; dashed: eventual.",
        "flowchart TD",
        "    subgraph workflow_layer[Workflows]",
    ]
    for name in sorted(workflows):
        lines.append(f'        workflow_{name}["{escape(name)}"]')
    lines.extend(["    end", "", "    subgraph brick_layer[Bricks]"])
    for name in names:
        lines.append(f'        brick_{name}["{node_label(name, contracts[name][1])}"]')
    lines.append("    end")
    edges = [
        f"    brick_{name} {'-.->' if mode == 'eventual' else '-->'} brick_{dependency}"
        for name in names
        for dependency, mode in sorted(contracts[name][0].items())
    ]
    edges.extend(
        f"    workflow_{name} --> brick_{dependency}"
        for name in sorted(workflows)
        for dependency in workflows[name]
        if dependency in contracts
    )
    if edges:
        lines.extend(["", *edges])
    top_level = [name for name in names if name not in depended_on]
    if top_level and len(top_level) != len(names):
        lines.extend([
            "",
            "    classDef topLevel stroke-width:3px",
            f"    class {','.join(f'brick_{name}' for name in top_level)} topLevel",
        ])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    root = parser.parse_args().root.resolve()
    bricks = root / "bricks"
    if not bricks.is_dir():
        print(f"{bricks}: bricks directory is missing", file=sys.stderr)
        return 1
    contracts = {
        path.name: read_contract(path)
        for path in sorted(bricks.iterdir())
        if path.is_dir() and not path.name.startswith((".", "__"))
    }
    if not contracts:
        print(f"{bricks}: no bricks to graph", file=sys.stderr)
        return 1
    workflows_root = root / "workflows"
    workflows = {
        path.name: read_workflow_contract(path)
        for path in sorted(workflows_root.iterdir())
        if path.is_dir() and not path.name.startswith((".", "__"))
    } if workflows_root.is_dir() else {}
    print(render(contracts, workflows), end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
