#!/usr/bin/env python3
"""Render Bend brick dependencies as Mermaid using the contract parser."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

try:
    from tools import lint_bricks
except ModuleNotFoundError:  # Direct execution adds tools/, not the repo root.
    import lint_bricks  # type: ignore[no-redef]


def read_contract(brick: Path) -> tuple[dict[str, str], tuple[str, ...]]:
    """Read dependency and ownership literals from one contract.bend."""
    root = brick.parents[1]
    lint = lint_bricks.Lint(root)
    contract = lint_bricks.lint_contract(brick, lint)
    if lint.errors:
        return {}, ()
    return contract.dependencies, contract.owned_state


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', "&quot;")


def node_label(name: str, owned_state: tuple[str, ...]) -> str:
    return "<br/>".join([escape(name), *(escape(item) for item in owned_state)])


def render(contracts: dict[str, tuple[dict[str, str], tuple[str, ...]]]) -> str:
    names = sorted(contracts)
    depended_on = {
        dependency
        for dependencies, _ in contracts.values()
        for dependency in dependencies
        if dependency in contracts
    }
    lines = [
        "%% Generated by tools/graph_bricks.py. Solid: orchestrated. Dashed: eventual.",
        "flowchart TD",
    ]
    for name in names:
        lines.append(f'    {name}["{node_label(name, contracts[name][1])}"]')
    edges = [
        f"    {name} {'-.->' if mode == 'eventual' else '-->'} {dependency}"
        for name in names
        for dependency, mode in sorted(contracts[name][0].items())
    ]
    if edges:
        lines.extend(["", *edges])
    top_level = [name for name in names if name not in depended_on]
    if top_level and len(top_level) != len(names):
        lines.extend(["", "    classDef topLevel stroke-width:3px", f"    class {','.join(top_level)} topLevel"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    root = parser.parse_args().root.resolve()
    bricks = root / "bricks"
    if not bricks.is_dir():
        print(f"{bricks}: bricks directory is missing", file=sys.stderr)
        return 1
    contracts = {
        path.name: read_contract(path)
        for path in sorted(bricks.iterdir())
        if path.is_dir() and not path.name.startswith((".", "__"))
    }
    if not contracts:
        print(f"{bricks}: no bricks to graph", file=sys.stderr)
        return 1
    print(render(contracts), end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
